services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: urlshortener
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
    restart: always

volumes:
  mongo_data:
